version: "3.7"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./stars:/webapp
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./stars/stars/.env
    #environment:
     #- POSTGRES_NAME=starsdb
      #- POSTGRES_USER=starsuser
      #- POSTGRES_PASSWORD=stars123
      #- POSTGRES_DB=starsdb
    depends_on:
      - cloudsqlproxy
    restart: always

# The proxy will help us connect to remote CloudSQL instance locally.
# Make sure to turn off any VPNs for the proxy to work.
  cloudsqlproxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      #- ./creds.json:/secrets/cloudsql/creds.json
      - ./data/db:/var/lib/posgresql/data
    ports:
      - 127.0.0.1:5432:5432
    command: /cloud_sql_proxy -instances="stars-356717:europe-west1-b:starsdb-id"=tcp:0.0.0.0:5432 #-credential_file=/secrets/cloudsql/creds.json
    restart: always #maybe on-failure would be enough?
