# Generated by Django 4.0.4 on 2022-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='geraete',
        ),
        migrations.AddField(
            model_name='workplace',
            name='geraete',
            field=models.ManyToManyField(to='starsApp.workplacedevice'),
        ),
    ]
