# Generated by Django 4.0.4 on 2022-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('A', 'Arm'), ('B', 'Baum')], max_length=150, verbose_name='Name'),
        ),
    ]
