# Generated by Django 4.0.4 on 2022-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsApp', '0002_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('FH', 'Frauenhofer'), ('VWS', 'VWS'), ('TEL', 'TU-Hochhaus')], max_length=150, verbose_name='Name'),
        ),
    ]
