# Generated by Django 4.0.4 on 2022-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsApp', '0002_remove_workplace_geraete_workplace_geraete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='nummer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, unique=True),
        ),
    ]
