# Generated by Django 4.0.4 on 2022-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsApp', '0002_alter_profileuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vorname'),
        ),
    ]
